# Generated by Django 6.0.1 on 2026-01-10 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asteroid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nasa_id', models.CharField(max_length=50, unique=True, verbose_name='NASA ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('absolute_magnitude', models.FloatField(blank=True, null=True, verbose_name='Абсолютная звёздная величина')),
                ('is_potentially_hazardous', models.BooleanField(default=False, verbose_name='Потенциально опасный')),
                ('nasa_jpl_url', models.URLField(blank=True, max_length=500, verbose_name='URL на сайте NASA JPL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Астероид',
                'verbose_name_plural': 'Астероиды',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Flyby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата сближения')),
                ('velocity_kmh', models.FloatField(verbose_name='Скорость (км/ч)')),
                ('miss_distance_km', models.FloatField(verbose_name='Дистанция промаха (км)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('asteroid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flybys', to='core.asteroid', verbose_name='Астероид')),
            ],
            options={
                'verbose_name': 'Сближение',
                'verbose_name_plural': 'Сближения',
                'ordering': ['-date'],
                'unique_together': {('asteroid', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_notes', models.TextField(blank=True, verbose_name='Заметки пользователя')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('asteroid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to='core.asteroid', verbose_name='Астероид')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Элемент списка отслеживания',
                'verbose_name_plural': 'Списки отслеживания',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'asteroid')},
            },
        ),
    ]
